version: "2"
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-76
    # Available channels https://github.com/codeclimate/codeclimate-rubocop/branches/all?utf8=%E2%9C%93&query=channel%2Frubocop
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
  scss-lint:
    enabled: true
  coffeelint:
    enabled: true
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/vendor/"
  - "**/*.d.ts"
  - "app/assets/javascripts/lib/"
  - "app/assets/stylesheets/disable_animations.scss"
