inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/fixtures/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'Gemfile.lock'
  CacheRootDirectory: tmp
Naming/FileName:
  ExpectMatchingDefinition: true
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'lib/tasks/*'
    - 'test/**/*'
    - 'config.ru'
Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'
    - 'app/views/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - 'scripts/**/*'
    - 'spec/**/*'
Style/MutableConstant:
  Enabled: true
  Exclude:
    - 'db/migrate/**/*'
Layout/EmptyLineAfterGuardClause:
  Enabled: true
  Exclude:
    - 'app/views/**/*'
Style/RedundantInterpolation:
  Enabled: true
  Exclude:
    - 'app/views/**/*'
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/spec_helper.rb'
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: true
  Max: 100
  AllowURI: true
  IgnoreCopDirectives: true
  Exclude:
    - config/routes.rb
Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 100
Style/AsciiComments:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
