---
addons:
  chrome: stable
  postgresql: 9.6
after_deploy:
  - "echo \"done deploying\""
before_install:
  - "nvm install 12.13.1"
  - "node --version"
  - "curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.2"
  - "export PATH=$HOME/.yarn/bin:$PATH"
  - "yarn --version"
  - "sudo locale-gen tr_TR.UTF-8"
  - "sudo /etc/init.d/postgresql stop"
  - "sudo /etc/init.d/postgresql start 9.6"
  - "gem update --system"
  - "gem install bundler -v 1.17.3"
before_script:
  - "bundle exec rake db:create"
branches:
  except:
    - master
cache:
  yarn: true
  directories:
    - vendor/bundle
    - node_modules
    - $HOME/.nvm
deploy:
  access_key_id:
    secure: $AWS_ACCESS_KEY_ID
  app: boyutluseyler
  bucket_name: "elasticbeanstalk-eu-central-1-760282670217"
  env: boyutluseyler-stage
  provider: elasticbeanstalk
  region: eu-central-1
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  on:
    repo: rokumatsumoto/boyutluseyler
    branch: staging
dist: xenial
env:
  global:
    - CI=true
    - RAILS_ENV=test
    - SIMPLECOV=true
    - TEST_ENV_NUMBER=''
    - secure: BR96SqaoI5r/Px8VlkhmTkMHBex9f5+wBhVDP84niUZWmKc6h92n9OJW76iSbQCGZZmW7r5k29MU5WMH1MGvcyj0WMP9TRkf2QzKfChlpRxJpdbe3/0Ko9Y2OUbtCW5nGaKliq3wkY0Nw8MsL21Enobp9iCr8v+3w5/AF0koEyUtLxPozJSusdMdfd+7lWX5k9u2a+OQowQMR1W2Amh3YOM5IeIWOrxe8xtypv0b6RBe4E9hT0QZi2d7YZumf/Ncnf9YvqVQkAQqAT0JlQJX3OfYkMYgCGS3XR5wClPX9H2QiXlAZL1gu55/c221tcNRMxjJRdPYlVQOfVrmeEasTuTo/bEYCqnryT2y5KiV9WzHB1tFdz2lOA3/eHpHK5dSaie6NIofAHwvnzkU7Qy0Te2BvAlEqqTABdOQ4XU0ZbOr9fsj7iF+jbFSDFgvd5FKyP9SH8Y/u+E+QTNfK+c1mADAM547bjoTSopYXsuSZ8u2l2LRMQxHOogt3bEaaZtT/E949w5fUXjk8OUwLwQkWKBmMhBKg42ZgG5ba/vZatuMjN14e4Lh2Q8LvqWpLNNI0mG8iPOm/tuS4UWpivt+pU43Z2tddmu7mCuBYohvWuqd0dMb8TeMELx3EyqvPKKsw/bHw0YqyXxFyL/GE2If9LzZHpCOTHaLBSmw7ZhoWGQ=
# https://github.com/travis-ci/travis-ci/issues/8051#issuecomment-335517982
if: tag IS blank
install:
  - "bundle install --path vendor/bundle"
  - "yarn"
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
language: ruby
notifications:
  email: false
  slack:
    on_failure: always
    on_success: always
    rooms:
      secure: OfIFa1u7oAsBLrtlNVa8UTnNUmzG/xO627Zcs7+gV8mZcyoP5pue83GNlZ9qAxGBEA1LOeFo7PkmguDYohe1mbhYbWrNGOUSaekF/6H5NV7lruY7NWdcIfE/5qsgIdDq8wwBKUaoMRcD6EQxodTkpMfK1J69QRfIM1WAN6KASZIMcsspcF/rXUPT4+lAboS5sdfcQsbVd0wvYC8ZnK7r88zHPeJ+bYZl95Yf6uQ/vr080P+fXtK5rUhjCWyI813c++Te75O+Ac/GD8uBlq9qiCOGKSX/mkqexTUbpOXySmj5IoBruNuRjcA8QK+VtjcvJs1iXMXPmPY338mFiFmwvJlpsKQr/VCr0dLW9sCFh/YIBDJooIdBVbiN2+t3VXnzyEXFR4WrAcr//kob3/F6v2ZsN1LBWh9uuXwxc3flJuGIdDYpZwWYwTYNv6z4eYF54ASA9EgpCyUjSRq8pzpO9ZonUcgV0q9R1wn5tWsHUO2LzmmjmQ3nXld9T7DoazKJU+WHTx8zmo653mXo/in/PBWTbo0g+5hfihVWKbHI3ZxpKiUD+nHigvbzlFgWEui75d++7BgmYOYJtXIzykdx1U+H8KPyES2XCKSL2NTPdjsXqfAMYjO6qQn23e9lmFzbaxLxYKZlkQfxgHTCwVSxYY7DltBzZvJTYZXHlxPJHuo=
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
rvm:
  - "2.5.5"
script:
  # https://github.com/usabilityhub/rails-erb-loader/issues/63#issuecomment-374791504
  - "DISABLE_SPRING=1 bundle exec rails webpacker:compile"
  - "bundle exec rake db:schema:load"
  - "./cc-test-reporter before-build"
  - "bundle exec rspec spec"
  - "./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.simplecov.json"
  - "./cc-test-reporter sum-coverage coverage/codeclimate.*.json"
  - "./cc-test-reporter upload-coverage"
  - "bundle exec bundle-audit check --update"
services:
  - postgresql
