addons:
  chrome: stable
  postgresql: '10'
before_install:
- gem update --system
- gem install bundler
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
branches:
  only:
  - master
cache:
  directories:
  - vendor/bundle
dist: xenial
env:
  global:
  - CI=true
  - RAILS_ENV=test
  - SIMPLECOV=true
  - secure: BR96SqaoI5r/Px8VlkhmTkMHBex9f5+wBhVDP84niUZWmKc6h92n9OJW76iSbQCGZZmW7r5k29MU5WMH1MGvcyj0WMP9TRkf2QzKfChlpRxJpdbe3/0Ko9Y2OUbtCW5nGaKliq3wkY0Nw8MsL21Enobp9iCr8v+3w5/AF0koEyUtLxPozJSusdMdfd+7lWX5k9u2a+OQowQMR1W2Amh3YOM5IeIWOrxe8xtypv0b6RBe4E9hT0QZi2d7YZumf/Ncnf9YvqVQkAQqAT0JlQJX3OfYkMYgCGS3XR5wClPX9H2QiXlAZL1gu55/c221tcNRMxjJRdPYlVQOfVrmeEasTuTo/bEYCqnryT2y5KiV9WzHB1tFdz2lOA3/eHpHK5dSaie6NIofAHwvnzkU7Qy0Te2BvAlEqqTABdOQ4XU0ZbOr9fsj7iF+jbFSDFgvd5FKyP9SH8Y/u+E+QTNfK+c1mADAM547bjoTSopYXsuSZ8u2l2LRMQxHOogt3bEaaZtT/E949w5fUXjk8OUwLwQkWKBmMhBKg42ZgG5ba/vZatuMjN14e4Lh2Q8LvqWpLNNI0mG8iPOm/tuS4UWpivt+pU43Z2tddmu7mCuBYohvWuqd0dMb8TeMELx3EyqvPKKsw/bHw0YqyXxFyL/GE2If9LzZHpCOTHaLBSmw7ZhoWGQ=
install:
- bundle install --path vendor/bundle
- bundle exec chromedriver-update
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
language: ruby
notifications:
  email: false
  matrix:
  - false
  slack:
    on_success: always
    on_failure: always
    secure: PwisNSmwK/vjCsB3Yc0m9udkMuDr9anPHnIL8ZmiKNjhghYFLJbTIwSFqZ+N/5M60H/dvQT915mfk+AFiZKBY9pvtXisEAViuPFg7Oc0reWjXJnEBid8F8oCYmuQIXbyg6DRb3Tq6K5jlk4qEy8AwcXHjHfsJtP9hYWsT7y345gqPGYyvIkNJl2iZibSXB0vQB8OuNba4SC0McqpW6Ks5F8T1q1jgfqWLxGfsgMHdmHuR9L4uTbPi6iSgS+YlWpEPMNkFLpRREPIabAyPupIz6G4rvqU2wfqKjc6Qm+Qwh5Qru/y5Wn0BRe7tm9meISiFJ2u/8VHDDbRWqkEIOTMwWN8M9cZOXG6oH6zleavhutLzpRt6Hauy2Qdf4UASLb/FLTQiUdoE7ZPIiuIouiAowYPT4NMnEiELrgV2YZJQUGQXT2E9rJpKlvQLdzQwgXEvoH6Gv8D7FxVKaLITZ6S6nHZdT7zhZkLCPK4XCdPVtFRltDt2Ul9qgPw1GZDyASITww2PqGYqK4rJVzzkeIZ8ttX9Mi8XCaSL1J8Jv7cmtZybEO5jo4ALzWYL4aQ5/nv6/0Gtq60E2a2nx5iIZViCHVKNk1YZk7q0bOCjsHvl52Oapt1U+pV244hzAHnYLinPF7s8ZnscIJVqouXAzXvWJNZHB1sqVS6ZqlBQpsZ9BM=
rvm:
- 2.5.3
services:
- postgresql
script:
- bundle exec rake db:schema:load
- "./cc-test-reporter before-build"
- bundle exec rspec spec
- "./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.simplecov.json"
- "./cc-test-reporter sum-coverage coverage/codeclimate.*.json"
- "./cc-test-reporter upload-coverage"
- bundle exec bundle-audit check --update
