export const SET_VALID_STATE = 'SET_VALID_STATE';
export const SET_EMPTY_STATE = 'SET_EMPTY_STATE';
export const SET_PENDING_STATE = 'SET_PENDING_STATE';
export const SET_AVAILABLE_STATE = 'SET_AVAILABLE_STATE';
export const SET_YOURS_STATE = 'SET_YOURS_STATE';

export const CLEAR_FIELD_VALIDATION_STATE = 'CLEAR_FIELD_VALIDATION_STATE';
export const CLEAR_FIELD_VALIDATION_STATE_MESSAGE = 'CLEAR_FIELD_VALIDATION_STATE_MESSAGE';

export const RENDER_YOURS_STATE = 'RENDER_YOURS_STATE';
export const RENDER_AVAILABLE_STATE = 'RENDER_AVAILABLE_STATE';
export const RENDER_PENDING_STATE = 'RENDER_PENDING_STATE';
export const RENDER_UNAVAILABLE_STATE = 'RENDER_UNAVAILABLE_STATE';
export const RENDER_STATE = 'RENDER_STATE';

export const SET_AVAILABILITY_STATE = 'SET_AVAILABILITY_STATE';
export const USERNAME_CHECK = 'USERNAME_CHECK';

export const SET_MARGIN_BOTTOM_USERNAME_FORM_GROUP = 'SET_MARGIN_BOTTOM_USERNAME_FORM_GROUP';
