shared: &shared
  direct_upload_provider: AWS # Google https://cloud.google.com/storage/docs/migrating
  direct_upload_access_key_id: <%= Boyutluseyler.credentials[:aws_s3][:access_key_id] %>
  direct_upload_secret_access_key: <%= Boyutluseyler.credentials[:aws_s3][:secret_access_key] %>
  direct_upload_bucket_name: <%= Boyutluseyler.credentials[:aws_s3][:bucket_name] %>
  direct_upload_region: <%= Boyutluseyler.credentials[:aws_s3][:region] %>
  direct_upload_acl: <%= Boyutluseyler.credentials[:aws_s3][:acl] %>
  direct_upload_endpoint: <%= Boyutluseyler.credentials[:aws_s3][:endpoint] %>
  direct_upload_success_action_status: <%= "\'#{Boyutluseyler.credentials[:aws_s3][:success_action_status]}\'" %>
  direct_upload_cache_control: public, max-age=315576000

  bucket_acl: <%= Boyutluseyler.credentials[:aws_s3][:acl] %>
  presigned_url_expires_in: 3600 # 1 hour
  cookie_domain: <%= Boyutluseyler.credentials[:cookie_domain] %>
  processed_bucket_name: <%= Boyutluseyler.credentials[:aws_s3][:processed_bucket_name] %>
  processed_endpoint: <%= Boyutluseyler.credentials[:aws_s3][:processed_endpoint] %>

development:
  <<: *shared

production:
  <<: *shared
