shared: &shared
  aws:
    region:
    access_key_id:
    secret_access_key:

  aws_s3:
    name: s3
    bucket_name:
    processed_bucket_name:
    access_key_id:
    secret_access_key:
    region:
    endpoint: https://ff0c44a8-117f-4091-a8dc-9b2ebac75bb7.s3.eu-central-1.amazonaws.com
    processed_endpoint: https://your-processed-bucket-name.s3.eu-central-1.amazonaws.com
    acl:
    success_action_status: '201'

  facebook_key:
  facebook_secret:

  google_key:
  google_secret:

  recaptcha_site_key:
  recaptcha_secret_key:

  redis:
    host: localhost
    port: 6379

  # amazon rds
  rds_db_name:
  rds_username:
  rds_password:
  rds_hostname:
  rds_port:

development:
  <<: *shared
  # Sending emails in development with Letter Opener https://github.com/fgrehm/letter_opener_web
  mail_sender: test@example.com

  website: localhost:3000

production:
  <<: *shared
  mail_sender:

  redis:
    host:
    port:
    url:

  send_grid_user_name:
  send_grid_password:
  send_grid_domain:
  send_grid_host:

  website:

  # See https://github.com/rokumatsumoto/boyutluseyler/pull/61
  cookie_domain:

test:
  <<: *shared
  mail_sender: test@example.com

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base:
