default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  collation: tr_TR.UTF-8
  ctype: tr_TR.UTF-8
  template: template0

development:
  <<: *default
  database: boyutluseyler_development

test:
  <<: *default
  database: boyutluseyler_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: <%= Rails.application.credentials[:rds_db_name] %>
  username: <%= Rails.application.credentials[:rds_username] %>
  password: <%= Rails.application.credentials[:rds_password] %>
  host: <%= Rails.application.credentials[:rds_hostname] %>
  port: <%= Rails.application.credentials[:rds_port] %>
